name: Build

on:
  push:
    branches: [ main ]
    paths:
      - 'template/**'
      - 'tutorial/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'template/**'
      - 'tutorial/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make font-noto-cjk ttf-freefont
            make
      - name: Collect
        run: |
          export GIT_HASH=$(git rev-parse --short "$GITHUB_SHA")
          mv tutorial/tutorial.pdf "tutorial-$GIT_HASH.pdf"
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Tutorial
          path: |
            tutorial-*.pdf
